
{
  "poolkeeper": {
    "nodePoolAnnotation": "cloud.google.com/gke-nodepool",
    "nodePools": [
      {
        "name": "workload",
        "keepOut": {
          "namespace": "kube-system"
        }
      }
    ]
  }
}
